# Generated by Django 4.1.13 on 2024-03-24 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200, null=True, verbose_name='File_Path')),
            ],
            options={
                'verbose_name_plural': 'PostImages',
            },
        ),
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('comment', models.CharField(max_length=200, verbose_name='comment')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='country')),
                ('prefectures', models.CharField(max_length=30, null=True, verbose_name='prefectures')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='city')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('favorites', models.PositiveIntegerField(default=0, verbose_name='favorites')),
                ('post_images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='post_img')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User_ID')),
            ],
            options={
                'verbose_name_plural': 'diary',
            },
        ),
    ]
