# Generated by Django 4.1.13 on 2024-04-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
