# Generated by Django 4.1.13 on 2024-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0002_delete_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='post_images',
        ),
        migrations.AddField(
            model_name='diary',
            name='post_image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='投稿画像'),
        ),
        migrations.AddField(
            model_name='diary',
            name='post_image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='投稿画像'),
        ),
        migrations.AddField(
            model_name='diary',
            name='post_image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='投稿画像'),
        ),
        migrations.AddField(
            model_name='diary',
            name='post_image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='投稿画像'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='市町村区'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.TextField(max_length=200, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='観光地の国'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='prefectures',
            field=models.CharField(max_length=30, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
