# Generated by Django 4.1.13 on 2024-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0004_prefectures_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefectures',
            name='id',
        ),
        migrations.AlterField(
            model_name='prefectures',
            name='prefecture_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='都道府県コード'),
        ),
    ]
