# Generated by Django 4.1.13 on 2024-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0005_remove_prefectures_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='id',
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='市区町村コード'),
        ),
    ]
