# Generated by Django 4.1.13 on 2024-04-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0007_alter_cities_prefecture_id_alter_diary_prefectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='travelog_app.cities', verbose_name='市町村区'),
        ),
    ]
