# Generated by Django 4.1.13 on 2024-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0010_remove_diary_likes_diary_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
