# Generated by Django 4.1.13 on 2024-05-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0011_alter_diary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefectures',
            name='prefecture_name',
            field=models.CharField(max_length=4, unique=True, verbose_name='都道府県名'),
        ),
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50, verbose_name='エリア名')),
                ('prefecture_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travelog_app.prefectures', to_field='prefecture_name', verbose_name='都道府県名')),
            ],
        ),
    ]
