# Generated by Django 4.1.13 on 2024-05-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0012_alter_prefectures_prefecture_name_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='prefecture_name',
            field=models.ForeignKey(db_column='prefecture_name', on_delete=django.db.models.deletion.PROTECT, to='travelog_app.prefectures', to_field='prefecture_name', verbose_name='都道府県名'),
        ),
    ]
