# Generated by Django 4.1.13 on 2024-05-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0014_remove_diary_city_diary_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='エリア名'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.PROTECT, to='travelog_app.areas', to_field='area_name', verbose_name='エリア'),
        ),
    ]
