# Generated by Django 4.1.13 on 2024-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog_app', '0015_alter_areas_area_name_alter_diary_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='エリア名'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='エリア'),
        ),
    ]
