# Generated by Django 4.1.13 on 2024-05-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelog_app', '0016_alter_areas_area_name_alter_diary_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('from_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_follow', to=settings.AUTH_USER_MODEL, verbose_name='フォローしているユーザー')),
                ('to_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='フォローされているユーザー')),
            ],
            options={
                'verbose_name_plural': 'from_follow',
            },
        ),
    ]
