# Generated by Django 4.1.13 on 2024-03-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name_plural": "CustomUser"},
        ),
    ]
