# Generated by Django 4.1.13 on 2024-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='ユーザー', max_length=20, verbose_name='ニックネーム'),
        ),
    ]
