# Generated by Django 4.1.13 on 2024-03-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                max_length=50, null="false", verbose_name="ニックネーム"
            ),
            preserve_default="false",
        ),
    ]
