# Generated by Django 4.1.13 on 2024-03-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_postimages_diary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="post_images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.postimages",
                verbose_name="Post_Img",
            ),
        ),
    ]
