# Generated by Django 4.1.13 on 2024-05-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_name_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='user.png', upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
