# Generated by Django 4.1.13 on 2024-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='', verbose_name='プロフィール画像'),
        ),
    ]
