# Generated by Django 4.1.13 on 2024-05-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_bio',
            field=models.CharField(blank=True, default='プロフィールです', max_length=20, null=True, verbose_name='プロフィール'),
        ),
    ]
